version: 2.1
jobs:
  build:
    docker:
      - image: paulflang/disfit
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.dev.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            apt-get install python3-venv -y
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install -e /root/project
            python3 -m pip install -r requirements.dev.txt
            echo "source /root/project/venv/bin/activate" >> $BASH_ENV
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.dev.txt" }}
          paths:
            - "venv"
  test_core:
    docker:
      - image: paulflang/disfit
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            apt-get install python3-venv -y
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install -e /root/project
            python3 -m pip install -r requirements.dev.txt
            echo "source /root/project/venv/bin/activate" >> $BASH_ENV
      - run: 
          name: test_core
          command: |
            . venv/bin/activate
            python3 -m pytest tests/test_core.py
  test_core:
    docker:
      - image: paulflang/disfit
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            apt-get install python3-venv -y
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install -e /root/project
            python3 -m pip install -r requirements.dev.txt
            echo "source /root/project/venv/bin/activate" >> $BASH_ENV
      - run: 
          name: test_core
          command: |
            . venv/bin/activate
            python3 -m pytest tests/test_petab_suite.py
  test_main:
    docker:
      - image: paulflang/disfit
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            apt-get install python3-venv -y
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install -e /root/project
            python3 -m pip install -r requirements.dev.txt
            echo "source /root/project/venv/bin/activate" >> $BASH_ENV
      - run:
          name: test main
          command: |
            . venv/bin/activate
            python3 -m pytest tests/test_main.py

workflows:
  version: 2.1
  test_build_core_main:
    jobs:
      - build
      - test_core:
          requires:
            - build
      - test_main:
          requires:
            - build
            - test_core