version: 2.1
jobs:
  Dependencies:
    docker:
      - image: paulflang/disfit
    # working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.dev.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: python3 -m pip install -r requirements.dev.txt
      - run:
          name: install pytest
          command: python3 -m pip install -U pytest
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.dev.txt" }}
          paths:
            - /usr/local/lib/python3.8/dist-packages
      # - store_artifacts:
      #   path: test-reports
      #   destination: test-reports
  test_core:
    docker:
      - image: paulflang/disfit
    # working_directory: ~/repo
    steps:
      - run:
          name: test_core
          command: python3 -m pytest tests/test_core.py
  test_main:
    docker:
      - image: paulflang/disfit
    # working_directory: ~/repo
    steps:
      - run:
          name: test main
          command: python3 -m pytest tests/test_core.py

workflows:
  version: 2.1
  test_build_core_main:
    jobs:
      - Dependencies
      - test_core:
          requires:
            - Dependencies
      - test_main:
          requires:
            - Dependencies
            - test_core